### ISSUE TITLE
Track Debian releases

### ISSUE THREAD

**Issue by jayfang** [pop-os/chromium#1]
Firstly I'm a n00b on how Linux distro's work, so apologies if I unintentionally waste anyone's time.

I'm running Pop OS, and as I understand it my Chromium version is pinned by this repo.  At time of writing it is on old version (80) while the upstream repo is on newer version (83). Given the security patches rolled out and needing to develop web software this approximately 7 month gap is an issue.

Ideal for me is that "Pop Shop" default Chromium install keeps up to date with Debian/Ubuntu latest Chromium release, but if there is an issue doing that, then I'd appreciate if could point me to a workaround.

**Comment by mmstick** [comment]
This repo doesn't actually do anything. Chromium 83 is currently in proposed for testing from Debian. We have to pull directly from Debian because Ubuntu does not maintain it anymore as a debian package.
